[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true

# Additional redirects for better SPA support
[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/trading"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/journal"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/analytics"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/new-trade"
  to = "/.netlify/functions/___netlify-handler"
  status = 200 